# Generated by Django 4.1.3 on 2023-01-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_remove_course_student_remove_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
