# Generated by Django 4.1.3 on 2023-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_remove_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.IntegerField(default=True),
        ),
    ]
